// Campaign Templates - Available templates for quick campaign creation
const CAMPAIGN_TEMPLATES = {
  nostalgicStory: {
    id: "nostalgic-story",
    title: "Nostalgic Stories",
    description: "Collect heartwarming stories from alumni about their college days",
    category: "Nostalgic Stories",
    duration: 14,
    formFields: [
      {
        fieldId: "story-title",
        fieldName: "storyTitle",
        fieldType: "text",
        label: "Story Title",
        placeholder: "Give your story a catchy title",
        required: true,
        maxLength: 100,
      },
      {
        fieldId: "story-content",
        fieldName: "storyContent",
        fieldType: "textarea",
        label: "Your Story",
        placeholder: "Share your favorite memory from your college days...",
        required: true,
        minLength: 50,
      },
      {
        fieldId: "batch-year",
        fieldName: "batchYear",
        fieldType: "select",
        label: "Batch Year",
        required: true,
        options: Array.from({ length: 30 }, (_, i) => 
          String(new Date().getFullYear() - i)
        ),
      },
      {
        fieldId: "department",
        fieldName: "department",
        fieldType: "select",
        label: "Department",
        required: true,
        options: ["Computer Science", "Electronics", "Mechanical", "Civil", "Others"],
      },
      {
        fieldId: "story-photo",
        fieldName: "storyPhoto",
        fieldType: "file",
        label: "College Photo (Optional)",
        placeholder: "Upload a photo from your college days",
        required: false,
      },
    ],
  },

  alumniSpotlight: {
    id: "alumni-spotlight",
    title: "Alumni in Spotlight",
    description: "Recognize and celebrate outstanding alumni achievements",
    category: "Alumni in Spotlight",
    duration: 14,
    formFields: [
      {
        fieldId: "alumnus-name",
        fieldName: "alumnusName",
        fieldType: "text",
        label: "Alumni Name",
        required: true,
      },
      {
        fieldId: "batch-year",
        fieldName: "batchYear",
        fieldType: "text",
        label: "Batch Year",
        required: true,
      },
      {
        fieldId: "current-role",
        fieldName: "currentRole",
        fieldType: "text",
        label: "Current Position/Title",
        required: true,
      },
      {
        fieldId: "company",
        fieldName: "company",
        fieldType: "text",
        label: "Organization/Company",
        required: true,
      },
      {
        fieldId: "achievement",
        fieldName: "achievement",
        fieldType: "textarea",
        label: "Major Achievements",
        placeholder: "Describe their notable achievements and contributions...",
        required: true,
      },
      {
        fieldId: "impact",
        fieldName: "impact",
        fieldType: "textarea",
        label: "Impact on Society/Industry",
        required: false,
      },
      {
        fieldId: "photo",
        fieldName: "photo",
        fieldType: "file",
        label: "Professional Photo",
        required: true,
      },
      {
        fieldId: "linkedin",
        fieldName: "linkedin",
        fieldType: "text",
        label: "LinkedIn Profile URL",
        required: false,
      },
    ],
  },

  entrepreneurStory: {
    id: "entrepreneur-story",
    title: "Entrepreneur Stories",
    description: "Inspire others by sharing your entrepreneurial journey",
    category: "Entrepreneur Stories",
    duration: 21,
    formFields: [
      {
        fieldId: "name",
        fieldName: "name",
        fieldType: "text",
        label: "Your Name",
        required: true,
      },
      {
        fieldId: "batch",
        fieldName: "batch",
        fieldType: "text",
        label: "Batch Year",
        required: true,
      },
      {
        fieldId: "startup-name",
        fieldName: "startupName",
        fieldType: "text",
        label: "Startup/Business Name",
        required: true,
      },
      {
        fieldId: "startup-description",
        fieldName: "startupDescription",
        fieldType: "textarea",
        label: "What does your startup do?",
        required: true,
      },
      {
        fieldId: "journey",
        fieldName: "journey",
        fieldType: "textarea",
        label: "Your Entrepreneurial Journey",
        placeholder: "How did you get started? What challenges did you face?",
        required: true,
      },
      {
        fieldId: "college-impact",
        fieldName: "collegeImpact",
        fieldType: "textarea",
        label: "How PSG CAS helped in your journey",
        required: false,
      },
      {
        fieldId: "lessons",
        fieldName: "lessons",
        fieldType: "textarea",
        label: "Key Lessons Learned",
        required: false,
      },
      {
        fieldId: "logo",
        fieldName: "logo",
        fieldType: "file",
        label: "Startup Logo/Photo",
        required: false,
      },
      {
        fieldId: "website",
        fieldName: "website",
        fieldType: "text",
        label: "Website URL",
        required: false,
      },
    ],
  },

  eventSurvey: {
    id: "event-survey",
    title: "Event Planning Survey",
    description: "Gather feedback and preferences for planning future events",
    category: "Survey",
    duration: 7,
    formFields: [
      {
        fieldId: "event-type",
        fieldName: "eventType",
        fieldType: "checkbox",
        label: "What type of events interest you?",
        required: true,
        options: ["Virtual Meet", "Physical Reunion", "Guest Lecture", "Workshop", "Networking Event"],
      },
      {
        fieldId: "preferred-month",
        fieldName: "preferredMonth",
        fieldType: "select",
        label: "Preferred Month for Event",
        required: true,
        options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      },
      {
        fieldId: "participation",
        fieldName: "willParticipate",
        fieldType: "radio",
        label: "Will you be able to participate?",
        required: true,
        options: ["Definitely Yes", "Maybe", "Probably Not"],
      },
      {
        fieldId: "speaker-suggestions",
        fieldName: "speakerSuggestions",
        fieldType: "textarea",
        label: "Guest Speaker/Expert Suggestions",
        placeholder: "Suggest alumni or experts you'd like to hear from",
        required: false,
      },
      {
        fieldId: "additional-feedback",
        fieldName: "feedback",
        fieldType: "textarea",
        label: "Additional Feedback",
        required: false,
      },
    ],
  },

  awardsRecognition: {
    id: "awards-recognition",
    title: "Alumni Awards & Recognition",
    description: "Nominate exceptional alumni for annual awards",
    category: "Awards & Recognition",
    duration: 30,
    formFields: [
      {
        fieldId: "nominee-name",
        fieldName: "nomineeName",
        fieldType: "text",
        label: "Nominee Name",
        required: true,
      },
      {
        fieldId: "nominee-batch",
        fieldName: "nomineeBatch",
        fieldType: "text",
        label: "Nominee Batch Year",
        required: true,
      },
      {
        fieldId: "award-category",
        fieldName: "awardCategory",
        fieldType: "select",
        label: "Award Category",
        required: true,
        options: ["Entrepreneur of the Year", "Social Impact Award", "Professional Excellence", "Young Achiever", "Life-Time Achievement"],
      },
      {
        fieldId: "reasons",
        fieldName: "reasons",
        fieldType: "textarea",
        label: "Why should they win this award?",
        required: true,
      },
      {
        fieldId: "nominator-name",
        fieldName: "nominatorName",
        fieldType: "text",
        label: "Your Name (Nominator)",
        required: true,
      },
      {
        fieldId: "nominator-batch",
        fieldName: "nominatorBatch",
        fieldType: "text",
        label: "Your Batch Year",
        required: true,
      },
      {
        fieldId: "nominator-email",
        fieldName: "nominatorEmail",
        fieldType: "email",
        label: "Your Email",
        required: true,
      },
    ],
  },

  placementDrive: {
    id: "placement-drive",
    title: "Placement Drive - Company Registration",
    description: "Register companies for campus placement drives",
    category: "Placement Drive",
    duration: 30,
    formFields: [
      {
        fieldId: "company-name",
        fieldName: "companyName",
        fieldType: "text",
        label: "Company Name",
        required: true,
      },
      {
        fieldId: "industry",
        fieldName: "industry",
        fieldType: "select",
        label: "Industry",
        required: true,
        options: ["IT", "Finance", "Manufacturing", "Consulting", "Others"],
      },
      {
        fieldId: "website",
        fieldName: "website",
        fieldType: "text",
        label: "Company Website",
        required: true,
      },
      {
        fieldId: "hr-contact",
        fieldName: "hrContact",
        fieldType: "text",
        label: "HR Contact Person",
        required: true,
      },
      {
        fieldId: "hr-phone",
        fieldName: "hrPhone",
        fieldType: "phone",
        label: "HR Phone Number",
        required: true,
      },
      {
        fieldId: "hr-email",
        fieldName: "hrEmail",
        fieldType: "email",
        label: "HR Email",
        required: true,
      },
      {
        fieldId: "positions",
        fieldName: "positions",
        fieldType: "textarea",
        label: "Job Positions Available",
        placeholder: "List positions and requirements",
        required: true,
      },
      {
        fieldId: "salary-range",
        fieldName: "salaryRange",
        fieldType: "text",
        label: "Salary Range (CTC)",
        required: true,
      },
      {
        fieldId: "selection-process",
        fieldName: "selectionProcess",
        fieldType: "textarea",
        label: "Selection Process",
        required: true,
      },
    ],
  },

  birthday: {
    id: "birthday-wishes",
    title: "Birthday Wishes",
    description: "Celebrate alumni birthdays with wishes",
    category: "Special Celebrations",
    duration: 1, // For a specific day
    formFields: [
      {
        fieldId: "celebrant-name",
        fieldName: "celebrantName",
        fieldType: "text",
        label: "Whose Birthday Are We Celebrating?",
        required: true,
      },
      {
        fieldId: "celebrant-batch",
        fieldName: "celebrantBatch",
        fieldType: "text",
        label: "Batch Year",
        required: true,
      },
      {
        fieldId: "wish",
        fieldName: "wish",
        fieldType: "textarea",
        label: "Birthday Wish/Message",
        placeholder: "Write your heartfelt birthday message...",
        required: true,
      },
      {
        fieldId: "wisher-name",
        fieldName: "wisherName",
        fieldType: "text",
        label: "Your Name",
        required: true,
      },
    ],
  },
};

module.exports = CAMPAIGN_TEMPLATES;